version: '2.1'
services:
  bot:
    build: .
    image: qqbot 
    volumes:
          - bot-db:/opt/app/ehforward_config/profiles/default/blueset.telegram
    depends_on:
      cqhttp:
            condition: service_healthy
       
  cqhttp:
    image: "richardchien/cqhttp"
    environment:
                - COOLQ_PORT=5700 
                - VNC_PASSWD=MAX8char
                - COOLQ_ACCOUNT=123456
                - CQHTTP_POST_URL=http://bot:8000 
                - CQHTTP_SERVE_DATA_FILES=yes
                - CQHTTP_ACCESS_TOKEN=ac0f790e1fb74ebcaf45da77a6f9de47
                - CQHTTP_POST_MESSAGE_FORMAT=array 
                - FORCE_ENV=true
    ports:
      -  "9000:9000" 
    volumes:
           - coolq-db:/home/user/coolq
    healthcheck:
        test: curl  -f http://localhost:$${COOLQ_PORT}/get_status?access_token=$${CQHTTP_ACCESS_TOKEN}
        interval: 10s
        timeout: 3s
        retries: 100
                       
volumes:
  coolq-db:
     external: true
  bot-db:
     external: true

