Client: CoolQ                         # 指定要使用的 QQ 客户端（此处为CoolQ）
CoolQ:
    type: HTTP                        # 指定 efb-qq-slave 与 酷Q 通信的方式 现阶段仅支持HTTP
    access_token: ac0f790e1fb74ebcaf45da77a6f9de47
    api_root: http://cqhttp:5700/  # 酷Q API接口地址/端口
    host: 0.0.0.0                   # efb-qq-slave 所监听的地址用于接收消息
    port: 8000                        # 同上
    is_pro: False                     # 若为酷Q Pro则为true，反之为false
    air_option:                       # 包含于 air_option 的配置选项仅当 is_pro 为 false 时才有效
        upload_to_smms: true          # 将来自 EFB主端(通常是Telegram) 的图片上传到 sm.ms 服务器并以链接的形式发送到 QQ 端
